<?php

namespace spice\koth;

use pocketmine\plugin\PluginBase;

class ApathosKOTH extends PluginBase
{
	private static ApathosKOTH $instance;
	private KOTHManager $kothManager;

	public function onEnable()
	{
		self::$instance = $this;
		$this->kothManager = new KOTHManager($this);
	}

	public function onDisable()
	{
		parent::onDisable(); // TODO: Change the autogenerated stub
	}


	/**
	 * @return ApathosKOTH
	 */
	public static function getInstance(): ApathosKOTH
	{
		return self::$instance;
	}

	/**
	 * @return KOTHManager
	 */
	public function getKOTHManager(): KOTHManager
	{
		return $this->kothManager;
	}

}